### ISSUE TITLE
Endianness/signed issues when reading

### ISSUE THREAD

**Issue by Phanabani** [RatchetModding/Replanetizer#16]
Hey! I'm trying out Replanetizer to learn about Ratchet's binary data and see if I can get any of the data out. I'm having issues both with the latest release and with my own builds where I'm getting errors from the file pointer being moved out of bounds of the file.

I looked into the data and it looks like the pointers at the start of the engine header are (unsigned?) little endian, but Replanetizer is attempting to read them as signed big endian, so I'm getting lots of negative ints for pointers. I added some little endian methods and tried using them to read in various pointers whenever I got errors, but then I also got more errors from ints being signed when they shouldn't be.

I wanted to ask - is there something fundamentally wrong with my game files? I'm assuming you haven't encountered these errors since it crashes while just trying to initially load the file. I'm on Windows and using RAC3 (PS3) files I ripped (which I looked at manually and look well-formed).

Also, thanks for the cool software! I've spent a little bit of time playing around in the past trying to reverse engineer some Ratchet stuff (albeit with ps2 files), so it's nice to see clearly defined structures for all this stuff that's confused me.

**Comment by MilchRatchet** [comment]
This is weird. Could you tell us which serial your RaC files belong to? For example, I am using files from the version with serial BCES-01503. Maybe there are some version differences that we were not aware of yet. Actually, I am unsure whether us reading the pointers as signed is correct anyway (no pointers are ever large enough for this to make a difference) but atleast for everyone involved in this project so far, big endian was correct.

Also, in case you are not on there yet, there is a discord for all RaC modding related stuff: https://discord.gg/KE8G5FA

**Comment by Phanabani** [comment]
Oh wow, so I have PCSA-00133, which is apparently the PS Vita release. I didn't know that there would be any difference there so I didn't even think to check. I'm guessing it's not worth even trying to support this, so I'll just try to switch over to your release. Thanks for your response and the discord link!

**Comment by Phanabani** [comment]
I've gotten it working with the version you recommended. It's so amazing to see this working, you all have done a great job.
