### ISSUE TITLE
Link viewport selection with model viewer

### ISSUE THREAD

**Issue by Phanabani** [RatchetModding/Replanetizer#30]
There should be a way to highlight the currently selected model from the viewport in the model viewer frame to save the user having to scroll a lot to search for the right model. This could either be an explicit button press or implicitly performed at all times (with a toggle option?).

**Comment by Phanabani** [comment]
This could be a two-way binding. Select a moby in the model viewer and it selects all models in the viewport (is multi-select supported?), or select a moby in the viewport and it selects it in the model viewer. Maybe have separate options for both, since always selecting multiple objects could be annoying.

**Comment by Phanabani** [comment]
I think it could be annoying for some people who might only want to go from viewport -> model viewer, and clicking a new model in the model viewer might surprise them by overwriting their selection with all of the new selections.

A good compromise could be to have the "automatically link selections" checkbox which enables automatic two-way binding, and then in the model viewer having two buttons to manually update the selection in each direction, model to viewport or viewport to model.

**Comment by Phanabani** [comment]
On hold until #50 is ready.

**Comment by MilchRatchet** [comment]
I just realized that this is already done. This was implemented in 8686fde14bb11ce347541df0a14d6332c9e068b4.
