### ISSUE TITLE
Hit detection for selecting objects can hit wireframes

### ISSUE THREAD

**Issue by Phanabani** [RatchetModding/Replanetizer#56]
If you manage to click on the wireframe of a selected object, the hit detection using `GL.ReadPixels` in `LevelFrame#GetObjectAtScreenPosition` returns `hit == 0`, instead of the object behind the wireframe. You can test this with my branch `Phana/feature/multi-select` -- clicking an object multiple times will toggle its selected status, and if you click on the wireframe (it's hard), it will stop toggling.

**Comment by Phanabani** [comment]
I'll be interested to see how you do this, because the hit detection algorithm looks like black magic to me. How is the object data like ID and type getting into the pixel data integer? Is it set with a uniform or something in the fragment shader?

**Comment by MilchRatchet** [comment]
I am closing this issue as it is no longer reproducible in 439050f. If the problem comes up again, reopen the issue.
