### ISSUE TITLE
FBX Exporter

### ISSUE THREAD

**Issue by Phanabani** [RatchetModding/Replanetizer#58]
An FBX exporter was requested for rigging support. This could also be useful for #36 to be able to export animations.

**Comment by UberNooga** [comment]
Collada (DAE) would also be a good option imo. I personally find it works more consistently than FBX does. Alternatively, GLTF is gaining some popularity too.

**Comment by MilchRatchet** [comment]
Since FBX is a proprietary file format, the decision was made to implement a GLTF exporter instead.
