### ISSUE TITLE
Error to build replanetizer program

### ISSUE THREAD

**Issue by GabrielGame311** [RatchetModding/Replanetizer#67]
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "git describe --long --always --dirty --exclude=* --abbrev=8" exited with code 9009.	Replanetizer	Replanetizer\Replanetizer.csproj	95

**Comment by MilchRatchet** [comment]
What operating system are using? Did you clone the git repository using git or did you download it through a different method?

**Comment by GabrielGame311** [comment]
I use windows 10

**Comment by MilchRatchet** [comment]
Did you clone the git repository using git or did you download it through a different method? If you didn't clone it using git, I recommend trying that. Otherwise, I will look to fix this issue in the near future.

**Comment by MilchRatchet** [comment]
Problem should no longer persist. If the error appears again open another issue and include details on what you did that led to the error.
